"""
Django settings for shipment_service project.

Generated by 'django-admin startproject' using Django 3.1.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(=7ji#ondt4b38rq-hd61dpw@49-wy@&!#a6c$z_4ds5ule4!w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    
    # Local apps
    'shipments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shipment_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shipment_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

MICROSERVICE_URLS = {
    'ORDER_SERVICE': 'http://localhost:8003/api',
    'PRODUCT_SERVICE': 'http://localhost:8001/api',
}

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# Shipping providers configuration
SHIPPING_PROVIDERS = {
    'EXPRESS': {
        'name': 'Express Shipping',
        'estimated_days': [1, 3],  # [min, max] days
        'tracking_url': 'https://express-shipping.example.com/track/',
    },
    'STANDARD': {
        'name': 'Standard Shipping',
        'estimated_days': [3, 7],  # [min, max] days
        'tracking_url': 'https://standard-shipping.example.com/track/',
    },
    'ECONOMY': {
        'name': 'Economy Shipping',
        'estimated_days': [5, 10],  # [min, max] days
        'tracking_url': 'https://economy-shipping.example.com/track/',
    },
}

# Demo shipping settings
SHIPPING_SETTINGS = {
    'PROCESSING_TIME_DAYS': 1,    # Days to process order before shipping
    'TRANSIT_TIME_MIN_DAYS': 2,   # Minimum transit time
    'TRANSIT_TIME_MAX_DAYS': 7,   # Maximum transit time
    'UPDATE_INTERVAL_HOURS': 12,  # Hours between status updates
    'DELIVERY_SUCCESS_RATE': 0.98,  # 98% successful deliveries
    'DELIVERY_ISSUE_RATE': 0.02,  # 2% delivery issues
}

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
